### ISSUE TITLE
Not working in nodejs

### ISSUE THREAD

**Issue by ryancat** [flozz/threadify#4]
This library is not working in nodejs envirionment. I have an issue on using Blob with nodejs. 

![screen shot 2018-05-07 at 17 03 38](https://user-images.githubusercontent.com/1658237/39730848-d5974e04-5218-11e8-8555-7918258acf30.png)

I think this is due to the nodejs buffer vs JS array buffer, which is mentioned here https://stackoverflow.com/questions/14653349/node-js-can%C2%B4t-create-blobs

**Comment by flozz** [comment]
Hello,

This library is intended to be used only in the browser, it cannot work on Node.js (as it manipulates, web worker, and blob URLs, that are only for browsers)

:)

**Comment by ryancat** [comment]
I found this in npm and directly used it's runkit to play with it -- yeah figured this library is only for client side usage. Thanks! I will close the issue.
