### ISSUE TITLE
need to include entire directory structure in zip file or just minified file

### ISSUE THREAD

**Issue by ArvindTrees** [flozz/threadify#9]
Sorry if this is a noob question. But to use threadify can I delete all the files in directory minus the .min file and just include the min file only? Or do I need to keep the whole directory for dependency reasons? 
For context, I'm not using nodejs, just testing this out on a simple html page on my localhost.

**Comment by flozz** [comment]
Hello,

You can keep only the `.min.js` file :)

**Comment by ArvindTrees** [comment]
thanks @flozz !
